### ISSUE TITLE
GlobalToolbarElement absolute position

### ISSUE THREAD

**Issue by gillhofer** [Caleydo/org.caleydo.view.furby#1]
I need a method for getting the absolute position of the GlobalToolbarElement.

Clusters should not be allowed to drift behind this bar. --> Need the position

**Comment by sgratzl** [comment]
when did you call the `getAbsoluteLocation()` It won't work during the init function, as it wasn't layouted yet.

**Comment by gillhofer** [comment]
I'd like to call a function (not necessary the getAbsolutoreLocation() ) directly in the force directed layout process. The Toolbar can be moved, and therefore the layout must know where to come up with space.

**Comment by sgratzl** [comment]
I got your point, but my question is why

``` java
Vec2f loc = globalElement.getAbsoluteLocation();
Vec2f size = globalElement.getSize();
```

isn't sufficient.

**Comment by gillhofer** [comment]
Just found out, it is sufficient.

/can be closed
