### ISSUE TITLE
Create a meaningful icon

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#110]

**Comment by sgratzl** [comment]
proposal: 

![icon128](https://f.cloud.github.com/assets/4129778/1581756/562098f0-51dd-11e3-8007-164fcfaac042.png)

**Comment by mstreit** [comment]
I like it. We should take the same colors that we use in the Caleydo logo.

**Comment by sgratzl** [comment]
![icon128](https://f.cloud.github.com/assets/4129778/1581829/ca52e5a0-51df-11e3-9a3d-c5a8f08ec447.png)

not that much of a difference
