### ISSUE TITLE
MouseWheel does not change the value of the spinner widgets

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#111]

**Comment by sgratzl** [comment]
scrolling down = mouse wheel?

if yes -> click on the view, I don't know why but there seems to be a focus problem, which I can't currently fix

**Comment by mstreit** [comment]
yes, mouse wheel. sorry.
ok.

**Comment by sgratzl** [comment]
please retest

btw. double-clicking or using the up/down button should also work

**Comment by mstreit** [comment]
works now.
