### ISSUE TITLE
Labels for focus cluster

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#12]
Labels should be shown for the focus cluster: gene names for rows and experiment names for cols.

**Comment by sgratzl** [comment]
the question is should be this a feature of the heatmap or the cluster using the heatmap?

**Comment by mstreit** [comment]
I guess it should be part of the heatmap implementation. An additional label col and row should be rendered on demand. By default we could decide whether to show the labels according to the number of rows/cols.

**Comment by sgratzl** [comment]
part of d3f23a35a659b3003e6a3c0b19b3fab3708ff8b2

using `setShowDimensionLabels or setShowRecordLabels` the presentation of the labels can be enabled

in addition the heatmap is now ready to be wrapped using a ScrollingDecorator, see SimpleScrollTest and the commented lines in ClusterElement line 148ff

-> using this label feature is up to you @gillhofer

**Comment by gillhofer** [comment]
![image](https://f.cloud.github.com/assets/4135093/517251/beefe46a-bed7-11e2-9f71-2b76a43636d9.png)

It would be nice, if there is 2 pixel space between the label and the heatmap. 
And it would also be nice, if i could ask the heatmap how much space the labels need

**Comment by gillhofer** [comment]
![image](https://f.cloud.github.com/assets/4135093/517468/59d915d6-bede-11e2-810d-ce5d5ab44239.png)
Currently i'm not really satisfied with my solution. 

What if the heatmap renders the labels on the right side / at the bottom?
The threshold sliders could then be moved to left, and the main problem with the bad cluster header is solved because it could be drawn like before.

Any other ideas?

**Comment by sgratzl** [comment]
ac7e8ed632ef39a25e4daf62831fe64a42ed05cd

api for queries the position/size of a column/record + label can be set to the left/top, none or right/bottom

**Comment by sgratzl** [comment]
> What if the heatmap renders the labels on the right side / at the bottom?
> The threshold sliders could then be moved to left, and the main problem with the bad cluster header is solved 
> because it could be drawn like before.

should be possible with the new api

> And it would also be nice, if i could ask the heatmap how much space the labels need

see HeatMapElement.TEXT_WIDTH

**Comment by sgratzl** [comment]
5ff9447 draft fish-eye spacing 

set the constructor of the ClusterElement class for usage
