### ISSUE TITLE
BiCluster Specific annotation

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#125]
the idea is to have a varying number of bicluster annotation for each bicluster. 

use case: 
- go-term enrichment analysis: bicluster x go-term -> p-value
- \+ go-term -> set of contained genes

task:
- add the top X go-terms as individual annotation columns to each bicluster
- encode contained by a simple yes / no color
- encode p-value as brightness of the color

**Comment by sgratzl** [comment]
with fake data: 

![2014-02-06 13_02_20-caleydo - multi20go_test cal](https://f.cloud.github.com/assets/4129778/2098147/0a2125f0-8f27-11e3-8042-cb5359d319e1.png)

**Comment by mstreit** [comment]
Looks great.
Can you make the lines in between the new columns a little thinner?
