### ISSUE TITLE
GLGraphhics drawText() ignores Color

### ISSUE THREAD

**Issue by gillhofer** [Caleydo/org.caleydo.view.furby#2]
g.color(new Color(0.5f,0.5f,0.5f,0.5f));
g.drawText("text", 0, 0, 100, 20);

Gets drawn in black with full opacity.

It seems like the set color is ignored.

**Comment by sgratzl** [comment]
what about `g.textColor(...)` ?

**Comment by gillhofer** [comment]
Ok solved. 

But why are there two different color setting mechanisms?

**Comment by sgratzl** [comment]
> But why are there two different color setting mechanisms?

I had two things in mind: 
1. implementation details that the textrenderer is quite different to the rest
2. I normally assume a different caller/callee convention for both, while a developer can't really assume anything   about the .color thing, the normal text color should be black. 
   therefore if I change the text color for a call I will change it back to black afterwards, just to avoid that I have to set the text color before each call to drawText
