### ISSUE TITLE
Find dataset for paper use case

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#21]
We need a publicly available dataset for the paper.
CMAP might be a good option: http://www.broadinstitute.org/cmap/

**Comment by mstreit** [comment]
TCGA data might be another option

**Comment by mstreit** [comment]
We should also take a look at the FABIA test datasets:
http://www.bioinf.jku.at/software/fabia/fabia.html

**Comment by sgratzl** [comment]
multi tissue dataset: https://www.broadinstitute.org/cgi-bin/cancer/datasets.cgi
