### ISSUE TITLE
Dynamically filter biclusters according to their size using slider

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#23]

**Comment by gillhofer** [comment]
implemented with https://github.com/sgratzl/caleydo-bicluster/commit/0274dfd5d6d85d48cce363178316a779a83d2f8b and https://github.com/sgratzl/caleydo-bicluster/commit/71614416a854a5411fd2ce260a40d12b7da897fa

The slider allows to set the smallest cluster size to at least x% of the size of the biggest cluster. Default is 0%.
