### ISSUE TITLE
Add an additional column and row to heatmap showing the actual L/Z values

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#24]
That is a very useful addition to give users a feeling for how good a bicluster is.
A greyscale can be used.
Min = 0, max = max threshold

**Comment by sgratzl** [comment]
RFC

**Comment by sgratzl** [comment]
one question of the bioinformatics was about the normalization, whether the max is globally or locally
 -> in the current version it is locally -> which they liked

**Comment by mstreit** [comment]
Looks very good!
Personally, I like a global max better. But if our users like the local version more, then let's leave it as it is.
