### ISSUE TITLE
Load bicluster thresholds contained in Fabia result and apply them as default

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#25]
By default, these thresholds can be used for each individual bicluster.

**Comment by sgratzl** [comment]
the fabia result method: `extractBic` delivers assignments and no thresholds, see also mail from 05.04.2013. 

I could try to reverse engineer it back to a threshold that can be used or as it should be the top N elements -> we could use #33 on a per bicluster level, too

**Comment by sgratzl** [comment]
the java side is prepared for loading threshold. In addition, the R load helper script is updated to generate a simple thresholding table similar to `extractBic`. 

I added another screenOnco project as demo
