### ISSUE TITLE
Add lock mode for clusters in focus 

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#26]
Feedback from Andreas Mayr: Add possibility to lock cluster in focus.
It should not receive threshold updates when the user activates the lock mode.

**Comment by gillhofer** [comment]
implemented with https://github.com/sgratzl/caleydo-bicluster/commit/c71d40b61d38cfe3628e3a43444c9895abe3daab with a button at the toolbar

**Comment by mstreit** [comment]
The icon is there, but the cluster still changes when manipulating the global thresholds

**Comment by gillhofer** [comment]
Thats strange. Only the size should change. The elements remains the same.

Or do you mean that the size and shape also should not change? If thats the case, you lose the visual consistency.

**Comment by mstreit** [comment]
OK, I see. It works. But I guess "locked" should mean that it does not change on any updates. atm it is the other way around.
By default it should be unlocked.

**Comment by gillhofer** [comment]
fixed https://github.com/sgratzl/caleydo-bicluster/commit/ad3a607a568281cdbb3b7956b18e0658de8b88aa
