### ISSUE TITLE
Sliders for dynamic change of absolute cluster size

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#33]
The button "Show only 15 elements per cluster" should be replaced with a dynamic slider that dynamically changes the max size of the clusters.
We actually need a slider for genes and samples respectively.

**Comment by sgratzl** [comment]
@gillhofer 

just to get your code right: 
there is currently a two step approach to filter items: 
1. via the executor job, considering the thresholds
2. within the cluster elements itself to consider the only 15 stuff during virtual array creation

right?

my question is why 1 and 2 aren't merged into one and everything is done with the executor job?

**Comment by gillhofer** [comment]
This is a legacy thing. It was easier implementable this way. 

I don't know the exact reason any more, but this could be changed at any time. It is not a "design choice", it was just simpler. 

I think this occurred by adding the local thresholds, but i'm not sure any more.
