### ISSUE TITLE
Adaptive band highlight

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#35]
Provide a slider that allows the user to focus on large overlaps between clusters or outliers.
The feature is similar to the one in VisBricks, see video at 2min 55s:
http://www.youtube.com/watch?v=_5J80uDTxD8

**Comment by sgratzl** [comment]
I don't know whether we really need this, as it seems to be that all bands are really small. Therefore we don't have the case like in StratomeX where could be interested in big/small overlaps

**Comment by mstreit** [comment]
With our current test datasets this is indeed not very interesting. However, I could imagine that there are datasets where it would make a lot of sense. We can leave it as it is for now and implement it when we have a real use case for it.
