### ISSUE TITLE
Force Directed Layout: add a modi where elements can be arranged in a better way.

### ISSUE THREAD

**Issue by gillhofer** [Caleydo/org.caleydo.view.furby#38]
There are 2 different possibilities. 
- Enlarge the drawing area. Would result in the best solution. 
  - Needs a proportional reposition of a clusters. (e.g Clusters on the right would move more to the middle)
  - may also need to lower the force factors.
  - toolbar position (also contributes to the layout)
  - edit getDistanceFromTopLeft() and getDistanceFromBottomRight()
- Shrink the clusters.
  Easy, only marginal side effects. But may need additional variation in the force factors. 
- Reduce repulsion.
  Should be the easiest way. Problem: Clusters could then be colliding. --> additional checks

**Comment by gillhofer** [comment]
I have implemented a few sliders for directly manipulating the forces of the layout. 

I think this issue is solved. The user can now optimize the layout individually.

https://github.com/gillhofer/org.caleydo.view.bicluster/commit/9b6a6d0e885ff359f2a3cb0c99a923b46a26a1f9

**Comment by mstreit** [comment]
Looks good.
Cluster shrinking would be nice too (but you don't need to implement this).

**Comment by sgratzl** [comment]
> Cluster shrinking would be nice too (but you don't need to implement this).

isn't this already possible: max. dimension size & max record size layout sliders?

**Comment by mstreit** [comment]
yes
