### ISSUE TITLE
MultiFormRenderer for BiCluster

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#42]
besides classical heatmaps following other views would be useful:
- histogram
- scatterplot
- enroute flat histogram

TODO: how to handle band connection for the different types

**Comment by mstreit** [comment]
We can handle band connections similar as we do it in StratomeX. The bands are connected with the brick, but the position does not have a meaning (except whether they connect vertically (= gene) or horizontally (= sample)).

**Comment by sgratzl** [comment]
no so change within the current strategy needed

**Comment by sgratzl** [comment]
in the current version a simple implementation for switching between heatmaps and histograms. 

What is missing is a right place for the buttons and the size adaptation to the new cluster elements (i.e. if changed to histograms the size of the clusters should change) but I have not yet an idea how to implement this

**Comment by sgratzl** [comment]
another problem: the heatmap is artificially enlarged during focus, such that the heatmap has still the same size but it takes the labels into account. The problem is that it doesn't work for histograms as we don't have here any labels yet.

**Comment by sgratzl** [comment]
> enroute flat histogram

@mstreit can you provide a screenshot how is should look like, please

**Comment by sgratzl** [comment]
> another problem: the heatmap is artificially enlarged during focus, such that the heatmap has still the same size but it takes the labels into account. The problem is that it doesn't work for histograms as we don't have here any labels yet.

workaround in f0154bd3faab5fce34ac5f1b737f92137b65efc1

**Comment by sgratzl** [comment]
> size adaptation to the new cluster elements (i.e. if changed to histograms the size of the clusters should change)

workaround in 3188f8f046f9bc5ac5bb5987cf191c246741f1f5 in the squared branch

**Comment by sgratzl** [comment]
> @mstreit can you provide a screenshot how is should look like, please

see Caleydo/caleydo#1520 -> there is now a new element LinearPlot, please check if I understood it right

**Comment by sgratzl** [comment]
@mstreit -> I would need some feedback regarding the LinearPlot

**Comment by mstreit** [comment]
I suggest to add a base line for data centered around 0. Also, it would be good to have an alternating shading between the lines, as it is hard to see the maximum length of the bar. Take a look at the enRoute CNV encoding.
