### ISSUE TITLE
Handle very low sample/gene threshold 

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#43]
When the thresholds are set to the minimum, the visualization freezes. 
Options how to handle this:
- Prevent user from choosing a very low threshold where the visualization makes no sense anymore. But what is the sane minimum?
- Other ideas?

**Comment by sgratzl** [comment]
the problem it depends on the current situation. I think the visualization freezes because the available space is overcrowded.

**Comment by sgratzl** [comment]
another problem is that the bands will always be repainted / relayouted, too. -> So it is hard that they will finally be cached.

**Comment by sgratzl** [comment]
auto scale down the global scaling factor if the filled ratio is larger then a experimental threshold. 

filled ratio = sum cluster area + toolbar areas / view area
