### ISSUE TITLE
Band fade to stub

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#50]
if you hover a node or band (see #48) the bands are faded out. 

A more radical approach would be to fade the bands to stubs. 

It could be implemented by fading in the center to the side, while rendering the whole band the whole time. 

three instances, time from top to bottom

![stub](https://f.cloud.github.com/assets/4129778/862176/567d60c8-f5e7-11e2-9db9-4261d792139e.png)

**Comment by sgratzl** [comment]
I implemented a simple version with the described approach. However it doesn't work with this simple trick in every case due to tesselation. 

Tesselation tries to find the optimal triangulation. Therefore it may occur - especially with thick bands - that a triangle will be rendered that start at one end and ends at the opposite end of the band. The problem is that the band ends will have a higher alpha value than the center but as the edges of the single big triangle are at the ends, artifacts occur

workaround: split the bands into real stubs instead of just faking them.

**Comment by sgratzl** [comment]
I fixed the problem by splitting the stubbed band into two ones. 

Maybe needs to fine-tuning regarding the animation, but I personally like it.

RFC

**Comment by mstreit** [comment]
Looks awesome! No comment atm.
