### ISSUE TITLE
Clusters connected by a selected band should not fade out

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#62]
When selecting a band, all other bands are reduced to stubs and also the clusters are drawn with lower opacity - which is fine. However, I would like to see all clusters that are connected by at least one selected band with full opacity.

**Comment by sgratzl** [comment]
see also #64 -> the same distance indicator could be used

**Comment by sgratzl** [comment]
selected band = selection -> don't fade out clusters with selections?

selected band = mouseOver or real selection?

**Comment by mstreit** [comment]
> selected band = selection -> don't fade out clusters with selections?

yes

> selected band = mouseOver or real selection?

I would say they should be visible for both selection states (mouse over and click selection)

**Comment by sgratzl** [comment]
the problem with the "don't fade out clusters with selections" approach is that if you have the bioinformatics scenario with: sample threshold = 0 -> you will always get some selections if you play around with clusters.

**Comment by mstreit** [comment]
Hm, but then the user could turn off the sample bands, right? In this case only clusters with visible connections should be fully opaque.
