### ISSUE TITLE
Changeable distance of bands that should be replaced by stubs

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#64]
This is a suggestion for a nice power feature. The default would be distance 1 (as it is now).
Any opinions how useful that would be?

**Comment by sgratzl** [comment]
what do you mean by distance
 a. graph distance: 1 = direct neighbors
 b. stub distance: = how "stubified" the items should be -> 0 = no stubs

I don't like the mouse wheel idea, as it isn't intuitive to use + the user may use it accidentally -> more in the menu some slider or so

**Comment by mstreit** [comment]
I mean the graph distance.
Yes, a slider could be better in this case.
