### ISSUE TITLE
Global Scaling

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#66]
in the current implementation one can scale a bicluster by using CTRL-MouseWheel. 

We could think of scaling the whole view (global scale factor) when the user performs the operation on the background and/or a slider

**Comment by mstreit** [comment]
yes, being able to globally scale all clusters by using the mouse wheel on the background would be useful.

**Comment by mstreit** [comment]
We could try this for all views. For the DVI for instance it would make a lot of sense.

**Comment by sgratzl** [comment]
you have to distinguish two scales: 
- the preference scaling factor manipulates the DIP conversion -> this can be done on a per view level, too -> e.g. similar to MS Word / LibreOffice...
- my suggestion just manipulates the scaling factors for the representation of the clusters, so the text, toolbars,... will have the same size = semantic scaling

**Comment by mstreit** [comment]
ok
