### ISSUE TITLE
Optimize initial position of newly added clusters

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#67]
Cluster are currently initially added to the layout at position 1000,1000. However, this produces situations where clusters end up far away from the connected ones (long bands). The layout is then far from optimal because other clusters are blocking the way to a better position (that has shorter bands). 

A solution could be to add new clusters in close proximity to the cluster with the highest number of shared elements.

**Comment by sgratzl** [comment]
the initial position of all clusters elements are layouted in a grid. 

an alternative solution is to center all connected elements and put isolated ones along the border.

**Comment by sgratzl** [comment]
e.g. take a look at the d3 force based initial positioning. 

it is somehow random for non-connected nodes and near to the first neighbor otherwise

**Comment by sgratzl** [comment]
part of 2ad3c8039a6a9123cc1bf4c1d040bb0dfb205447
