### ISSUE TITLE
Find relevant pathways for biclusters using GSEA and Lineup

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#70]
Users should be able to select a bicluster, which genes are then the input for a GSEA computation. The GSEA resulting pathway list should be shown in LineUp. Users can then select a pathway which can then be displayed as a separate brick next to the selected biclusters, connected by a full band.

Besides GO term search, this seems to be the way how our users confirm the relevance of a bicluster (see FABIA paper).

**Comment by sgratzl** [comment]
the biggest problem is that the pathway view is not yet ported to GLElements
