### ISSUE TITLE
L/Z value visualization on cluster border is too subtle

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#75]
Suggestions for improvement:
- Make wider when cluster is in focus
- We should use full gradient (black to white). Atm I only see very light grey values
- Indicate 0 with a line inside the gradient box.
- Check correctness of encoded values. In some cases the value drops for the last element, which is not expected.

**Comment by sgratzl** [comment]
> Indicate 0 with a line inside the gradient box.

I assume the raw 0 value and not the the gradient 0 value, right

**Comment by mstreit** [comment]
> I assume the raw 0 value and not the the gradient 0 value, right

yes

**Comment by sgratzl** [comment]
fixed in one of https://github.com/sgratzl/org.caleydo.view.bicluster/compare/3c380d1460...d2f5221d4b
