### ISSUE TITLE
Adaptive scaling of focus neighboring clusters

### ISSUE THREAD

**Issue by gillhofer** [Caleydo/org.caleydo.view.furby#8]
...depending on.
- Focused cluster
- Connections to the focused cluster

**Comment by sgratzl** [comment]
may require some scaling but in general the stuff is implemented. 

We could even completely hide non connected clusters, or in a distance of 2...

**Comment by mstreit** [comment]
Very nice.
I think we should try hiding non-connected clusters by default (only for the focus mode of course).

**Comment by sgratzl** [comment]
see also #64 -> same distance could be used
