### ISSUE TITLE
When turning off gene/sample connections clusters should not disappear

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#81]
Feedback from session with Andreas M.

**Comment by sgratzl** [comment]
in which scenario?

focus cluster + max distance?

**Comment by mstreit** [comment]
yes

**Comment by mstreit** [comment]
use case: on a smaller screen it is almost impossible to add clusters (at distance 1 for instance) when one cluster is in focus. without bands, the clusters could be arranged more easily in the free space.

**Comment by sgratzl** [comment]
currently turning off gene / sample bands, mean that they aren't:
1. rendered
2. considered for layouting
3. computed

we would need to differ between 1,2 and 3. e.g. in the standard bioinformatics setup with sample threshold 0, all samples are shared, but should not considered for 1, 2, and 3 even in this issue scenario.

**Comment by sgratzl** [comment]
is this still an issue with the new layout implementation?

or do it just for the focus mode?

**Comment by sgratzl** [comment]
wontfix
