### ISSUE TITLE
Threshold slider background probability gradient

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#95]
to highlight the correction between the probability and the treshold, we could use a gradient background in the threshold sliders

**Comment by mstreit** [comment]
yes!

**Comment by mstreit** [comment]
The slider background gradient does not correspond to the probability encoding shown on the sides of the clusters.

**Comment by mstreit** [comment]
The bicluster probabilities hardly reach a dark grey because of the linear gradient. This makes it hard to interpret the cluster strength.

**Comment by sgratzl** [comment]
please define the normalization function that should be used to convert a membership degree (unknown range) to 0 (white) ...1 (black)?

including globally or locally option

**Comment by mstreit** [comment]
I just found out that this very much depends on the loaded dataset.

**Comment by sgratzl** [comment]
so the goal is clip the probability range. -> How should the user set that value?

**Comment by sgratzl** [comment]
is this still an issue?
